import { Department, CampTimelineItem, FaqItem, Application, CampStat } from "./types";

export const CAMP_INFO = {
  nameTh: "ค่ายเทคโนโลยีวิชาการ จับมือน้องคลิก ครั้งที่ 20",
  nameEn: "ComClick Camp #20",
  shortName: "Comclick 20",
  sloganTh: "ก้าวสู่ทศวรรษที่ 2 สานฝันเทคโนโลยีสู่น้องๆ คลิกอนาคตไปด้วยกัน",
  sloganEn: "Step into the 2nd Decade: Empowering Young Minds through Tech",
  organizerTh: "สาขาวิชาคอมพิวเตอร์ศึกษาและเทคโนโลยีดิจิทัล คณะศึกษาศาสตร์ มหาวิทยาลัยขอนแก่น",
  organizerEn: "Department of Computer Education, Faculty of Education, Khon Kaen University",
  campDates: "17 - 19 ตุลาคม 2569",
  prepDates: "10 - 16 ตุลาคม 2569",
  locationTh: "คณะศึกษาศาสตร์ มหาวิทยาลัยขอนแก่น และ อาคารศูนย์เทคโนโลยีสารสนเทศ",
  registrationDeadline: "30 กันยายน 2569 เวลา 23:59 น.",
  contactEmail: "comclickcamp.kku@gmail.com",
  contactPhone: "089-123-4567, 084-987-6543",
  facebookPage: "ค่ายเทคโนโลยีวิชาการ จับมือน้องคลิก คณะศึกษาศาสตร์ มข.",
  instagram: "@comclick.kku",
  lineOfficial: "@comclick20",
};

export const DEPARTMENTS: Department[] = [
  {
    id: "academic",
    nameTh: "ฝ่ายวิชาการ (Academic & AI Lab)",
    nameEn: "Academic & Workshop Specialist",
    badge: "วิชาการ & โค้ดดิ้ง",
    icon: "Code2",
    color: "#5e97d3",
    shortDesc: "ออกแบบหลักสูตร วางแผนบทเรียน สอน Coding, AI, Robotics และดูแลกิจกรรมวิชาการ",
    description:
      "หัวใจสำคัญในการถ่ายทอดความรู้ด้านคอมพิวเตอร์และเทคโนโลยี ออกแบบใบงาน กิจกรรม Hands-on โค้ดดิ้ง ปัญญาประดิษฐ์ (AI) ไมโครบิต (Micro:bit) และโครงงานนวัตกรรมดิจิทัลสำหรับน้องๆ มัธยม",
    responsibilities: [
      "ร่วมออกแบบและพัฒนาหลักสูตรค่ายด้าน Programming / AI / IoT / Web Tech",
      "เป็นวิทยากรประจำห้องปฏิบัติการและพี่ประจำกลุ่ม Workshop",
      "จัดเตรียมสื่อการสอน เอกสาร และอุปกรณ์คอมพิวเตอร์ที่ใช้ในการเรียนรู้",
      "ให้คำปรึกษาน้องค่ายในการทำมินิโปรเจกต์ (Hackathon / Mini Project)",
    ],
    qualifications: [
      "มีทักษะพื้นฐานด้านการเขียนโปรแกรม หรือ เทคโนโลยีดิจิทัล (ไม่จำกัดภาษา)",
      "มีความสามารถในการอธิบายเรื่องยากให้เข้าใจง่าย มีความอดทนและใจเย็น",
      "มีใจรักในการถ่ายทอดความรู้และอยากส่งต่อแรงบันดาลใจ",
      "สามารถเข้าร่วมซ้อมสอนและเตรียมแล็บก่อนเปิดค่ายได้",
    ],
    openSlots: 18,
    tags: ["Coding", "AI & Data", "Hands-on", "Teaching"],
    bannerGradient: "from-[#5e97d3]/20 via-[#fbf3e0]/40 to-white",
  },
  {
    id: "recreation",
    nameTh: "ฝ่ายกิจกรรมพิเศษและนันทนาการ (Special Activities & Recreation)",
    nameEn: "Special Activities & Recreation",
    badge: "สันทนาการ & กิจกรรม",
    icon: "Sparkles",
    color: "#eccb7d",
    shortDesc: "สร้างรอยยิ้ม เอนเตอร์เทน นำเกม ร้องเพลง กิจกรรมเชื่อมสัมพันธ์ และดูแลพิธีกร",
    description:
      "ผู้สร้างความสุข เสียงหัวเราะ และบรรยากาศที่อบอุ่นเป็นกันเองตั้งแต่นาทีแรกจนถึงวันจบค่าย ควบคุมเวที กิจกรรมเปิด-ปิด และเกมกระชับมิตร",
    responsibilities: [
      "คิดและดำเนินกิจกรรมสันทนาการ ละลายพฤติกรรม (Icebreaking) และ Walk Rally",
      "เป็นพิธีกร (MC) เวทีกิจกรรมหลักและการแสดงรอบกองไฟ / Comclick Night",
      "นำร้องเพลง เต้นสันทนาการ และรักษาพลังงานบวกตลอดค่าย",
      "ควบคุมลำดับเวลาและจังหวะของกิจกรรมกลางแจ้งและห้องประชุม",
    ],
    qualifications: [
      "กล้าแสดงออก มีความมั่นใจ บุคลิกภาพร่าเริงแจ่มใส พลังงานล้นเหลือ",
      "มีไหวพริบปฏิภาณ แก้ไขสถานการณ์เฉพาะหน้าบนเวทีได้ดี",
      "รักงานเอนเตอร์เทนและชอบสร้างเสียงหัวเราะให้ผู้อื่น",
    ],
    openSlots: 14,
    tags: ["MC", "Icebreaking", "Stage Performance", "High Energy"],
    bannerGradient: "from-[#eccb7d]/20 via-[#fbf3e0]/40 to-white",
  },
  {
    id: "tech-pr",
    nameTh: "ฝ่ายเทคโนโลยีและประชาสัมพันธ์ (Technology & PR)",
    nameEn: "Technology & Public Relations",
    badge: "เทคโนโลยี & มีเดีย",
    icon: "Camera",
    color: "#d98e89",
    shortDesc: "ถ่ายภาพ วิดีโอ ผลิตสื่อกราฟิก ดูแลระบบเทคโนโลยีดิจิทัล และประชาสัมพันธ์ค่าย",
    description:
      "บอกเล่าเรื่องราวความประทับใจของค่ายผ่านเลนส์และงานดีไซน์ ดูแลสื่อประชาสัมพันธ์ สื่อโซเชียลมีเดีย สรุปวิดีโอประจำวัน (Daily Recap) และระบบเทคโนโลยีค่าย",
    responsibilities: [
      "บันทึกภาพนิ่งและวิดีโอกิจกรรมตลอดทุกช่วงเวลาของค่าย",
      "ตัดต่อวิดีโอไฮไลต์ประจำวัน (Daily Highlight) และวิดีโอปัจฉิมนิเทศ",
      "ออกแบบกราฟิก สื่อประชาสัมพันธ์ โปสเตอร์ และเกียรติบัตร",
      "ดูแลระบบเว็บไซต์ Live Streaming และช่องทาง Social Media",
    ],
    qualifications: [
      "มีทักษะการถ่ายภาพ ถ่ายวิดีโอ หรือใช้โปรแกรมตัดต่อ/ออกแบบ",
      "มีมุมมองศิลปะ มีความคิดสร้างสรรค์ เล่าเรื่องได้น่าสนใจ",
      "สามารถส่งไฟล์งานตรงตามเวลาที่กำหนดระหว่างค่าย",
    ],
    openSlots: 12,
    tags: ["Photography", "Graphic Design", "Video Editing", "Tech Support"],
    bannerGradient: "from-[#d98e89]/20 via-[#fbf3e0]/40 to-white",
  },
  {
    id: "fundraising",
    nameTh: "ฝ่ายจัดหาทุน (Fundraising & Sponsorship)",
    nameEn: "Fundraising & Sponsorship Specialist",
    badge: "จัดหาทุน & สปอนเซอร์",
    icon: "Coins",
    color: "#b08b5f",
    shortDesc: "ติดต่อประสานงานผู้สนับสนุน จัดหางบประมาณ ของรางวัล และสิทธิประโยชน์ของค่าย",
    description:
      "ฝ่ายขับเคลื่อนทรัพยากร จัดทำ Proposal เสนอโครงการแก่ผู้สนับสนุนทั้งภาครัฐและเอกชน ดูแลสิทธิประโยชน์ มอบของที่ระลึก และบริหารจัดการทุนสนับสนุนโครงการ",
    responsibilities: [
      "จัดทำเอกสารและข้อเสนอโครงการสำหรับขอรับการสนับสนุน (Sponsorship Proposal)",
      "ติดต่อประสานงานและเจรจากับผู้สนับสนุนภายนอกและศิษย์เก่า",
      "ดูแลสิทธิประโยชน์ โลโก้บูธ และของรางวัลสำหรับน้องค่าย",
      "จัดทำเอกสารขอบคุณและสรุปผลประโยชน์ที่ผู้สนับสนุนได้รับ",
    ],
    qualifications: [
      "มีทักษะการสื่อสาร เจรจาต่อรอง และการนำเสนออย่างมืออาชีพ",
      "มีความรับผิดชอบสูง บุคลิกภาพน่าเชื่อถือ และมีความกระตือรือร้น",
      "สามารถประสานงานกับองค์กรภายนอกได้อย่างคล่องตัว",
    ],
    openSlots: 8,
    tags: ["Fundraising", "Sponsorship", "Negotiation", "Partnership"],
    bannerGradient: "from-[#b08b5f]/20 via-[#fbf3e0]/40 to-white",
  },
  {
    id: "discipline",
    nameTh: "ฝ่ายปกครอง (Student Discipline & Governance)",
    nameEn: "Discipline & Governance Officer",
    badge: "ปกครอง & ระเบียบวินัย",
    icon: "ShieldAlert",
    color: "#132338",
    shortDesc: "ดูแลระเบียบวินัย ความปลอดภัย และสวัสดิภาพความเป็นอยู่ของน้องค่ายตลอด 24 ชั่วโมง",
    description:
      "ฝ่ายดูแลความเรียบร้อย ความปลอดภัย การตรงต่อเวลา และกฎระเบียบของค่าย ประสานงานการตรวจตราหอพัก และดูแลสวัสดิภาพของน้องค่ายและสตาฟทุกคน",
    responsibilities: [
      "ดูแลความเรียบร้อยและความปลอดภัยบริเวณพื้นที่จัดค่ายและหอพัก",
      "กำกับดูแลเรื่องเวลา การรวมแถว และระเบียบวินัยของน้องค่าย",
      "ตรวจเช็กความพร้อมและการเข้าห้องพักของน้องค่ายในแต่ละคืน",
      "ประสานงานแก้ไขปัญหาเฉพาะหน้าเกี่ยวกับความประพฤติและความปลอดภัย",
    ],
    qualifications: [
      "มีความเป็นผู้นำ หนักแน่น สุภาพ และมีวุฒิภาวะทางอารมณ์สูง",
      "มีความละเอียดรอบคอบ ช่างสังเกต และตื่นตัวต่อสถานการณ์รอบตัว",
      "สามารถอยู่เวรดูแลความปลอดภัยในช่วงเวลากลางคืนได้",
    ],
    openSlots: 10,
    tags: ["Discipline", "Security", "Leadership", "Safety Patrol"],
    bannerGradient: "from-[#132338]/20 via-[#fbf3e0]/40 to-white",
  },
  {
    id: "registration",
    nameTh: "ฝ่ายทะเบียน วัดและประเมินผล (Registration & Evaluation)",
    nameEn: "Registration, Data & QA",
    badge: "ทะเบียน & ประเมินผล",
    icon: "ClipboardCheck",
    color: "#5e97d3",
    shortDesc: "จัดการระบบลงทะเบียน ตรวจสอบรายชื่อ แจกของที่ระลึก และประเมินผลสัมฤทธิ์ค่าย",
    description:
      "ฝ่ายดูแลความถูกต้องของข้อมูลผู้เข้าร่วม ป้ายชื่อ เสื้อค่าย เอกสารลงทะเบียน ของที่ระลึก สถิติการเข้าเรียน และสรุปผลแบบประเมินโครงการ",
    responsibilities: [
      "ดูแลจุดลงทะเบียน Check-in รับส่งน้องค่ายและสตาฟ",
      "จัดการระบบข้อมูล จัดสรรห้องพัก และเตรียมป้ายชื่อ/ของที่ระลึก",
      "จัดทำแบบประเมินความพึงพอใจและสรุป Data Dashboard สถิติค่าย",
      "ประสานงานออกเกียรติบัตรอิเล็กทรอนิกส์และเอกสารรับรอง",
    ],
    qualifications: [
      "มีความละเอียดรอบคอบ ไม่ตกหล่นในเรื่องเอกสารและตัวเลข",
      "มีทักษะในการใช้ Google Sheets, Excel หรือเครื่องมือจัดการข้อมูล",
      "สุภาพ ใจเย็น มีใจรักบริการในการต้อนรับผู้ปกครองและน้องค่าย",
    ],
    openSlots: 8,
    tags: ["Data Management", "Organization", "Check-in", "Analytics"],
    bannerGradient: "from-[#5e97d3]/20 via-[#fbf3e0]/40 to-white",
  },
  {
    id: "coordination",
    nameTh: "ฝ่ายประสานงาน (Coordination & Liaison)",
    nameEn: "Camp Coordination & Liaison",
    badge: "ประสานงาน & ดูแลน้อง",
    icon: "HeartHandshake",
    color: "#d98e89",
    shortDesc: "ประสานงานทุกภาคส่วน ดูแลพี่เลี้ยงประจำกลุ่ม และประสานงานคณาจารย์วิทยากร",
    description:
      "สะพานเชื่อมการทำงานระหว่างทุกฝ่าย คณาจารย์ วิทยากรภายนอก และดูแลพี่เลี้ยงประจำกลุ่มน้องค่าย ให้ทุกกิจกรรมดำเนินไปอย่างราบรื่น",
    responsibilities: [
      "ประสานงานคณาจารย์ วิทยากรพิเศษ และหน่วยงานภายนอกที่เกี่ยวข้อง",
      "บริหารจัดการและดูแลพี่เลี้ยงประจำกลุ่มน้องค่าย (Mentor)",
      "ติดตามความคืบหน้าของแต่ละกิจกรรมและแจ้งเตือนลำดับขั้นตอน",
      "รับเรื่องและประสานงานแก้ไขปัญหาหน้างานระหว่างฝ่ายต่างๆ",
    ],
    qualifications: [
      "มีทักษะการสื่อสารมนุษยสัมพันธ์ดีเยี่ยม เข้ากับคนง่ายและใจเย็น",
      "มีไหวพริบในการแก้ปัญหาเฉพาะหน้าและมีความยืดหยุ่นสูง",
      "มีความรับผิดชอบสูงและตรงต่อเวลา",
    ],
    openSlots: 16,
    tags: ["Coordination", "Communication", "Liaison", "Problem Solving"],
    bannerGradient: "from-[#d98e89]/20 via-[#fbf3e0]/40 to-white",
  },
  {
    id: "medical",
    nameTh: "ฝ่ายพยาบาล (Medical & Healthcare)",
    nameEn: "Welfare, Safety & First Aid",
    badge: "พยาบาล & สุขภาพ",
    icon: "ShieldAlert",
    color: "#d98e89",
    shortDesc: "ดูแลสุขภาพ ปฐมพยาบาลเบื้องต้น ดูแลน้องป่วย และรักษาความปลอดภัยตลอดค่าย",
    description:
      "หน่วยพิทักษ์ความปลอดภัยของทุกคนในค่าย จัดเตรียมยาสามัญ ประเมินอาการเจ็บป่วย ดูแลผู้แพ้อาหารหรือมีโรคประจำตัว และประสานงานโรงพยาบาลฉุกเฉิน",
    responsibilities: [
      "จัดเตรียมกระเป๋าพยาบาล ยา และอุปกรณ์ปฐมพยาบาลเบื้องต้น",
      "ประจำห้องพยาบาล คอยดูแลน้องค่ายและพี่ค่ายที่มีอาการป่วยหรือบาดเจ็บ",
      "ตรวจตราความปลอดภัยบริเวณหอพัก จุดทำกิจกรรม และการเดินทาง",
      "ติดตามอาหารสำหรับผู้มีอาการแพ้เฉพาะบุคคลอย่างใกล้ชิด",
    ],
    qualifications: [
      "มีความรู้เรื่องการปฐมพยาบาลเบื้องต้น (First Aid / CPR จะพิจารณาเป็นพิเศษ)",
      "เป็นคนใจเย็น มีสติรอบคอบในการจัดการเหตุฉุกเฉิน",
      "เอาใจใส่ อ่อนโยน และมีความตื่นตัวอยู่เสมอ",
    ],
    openSlots: 8,
    tags: ["First Aid", "Health & Safety", "Empathy", "Emergency Care"],
    bannerGradient: "from-[#d98e89]/20 via-[#eccb7d]/20 to-white",
  },
  {
    id: "protocol",
    nameTh: "ฝ่ายพิธีการและปฏิคม (Protocol & Hospitality)",
    nameEn: "Protocol, Reception & Hospitality",
    badge: "พิธีการ & ปฏิคม",
    icon: "Award",
    color: "#eccb7d",
    shortDesc: "ดูแลลำดับพิธีการ พิธีเปิด-ปิด ต้อนรับแขกผู้มีเกียรติ และจัดเตรียมของที่ระลึก",
    description:
      "ผู้รังสรรค์ความสง่างามและความประทับใจ ดูแลลำดับขั้นตอนพิธีเปิด พิธีปิด พิธีบายศรีสู่ขวัญ ต้อนรับผู้บริหาร คณาจารย์ แขกผู้มีเกียรติ และจัดเตรียมของที่ระลึก",
    responsibilities: [
      "จัดทำสคริปต์และกำกับดูแลลำดับพิธีการในพิธีเปิดและพิธีปิดค่าย",
      "ต้อนรับและดูแลอำนวยความสะดวกแก่ผู้บริหาร คณาจารย์ และแขกผู้มีเกียรติ",
      "จัดเตรียมพานพุ่ม มาลัย ของที่ระลึก และเกียรติบัตรสำหรับแขกพิเศษ",
      "ดูแลพิธีการบายศรีสู่ขวัญและกิจกรรมประเพณีอันทรงคุณค่า",
    ],
    qualifications: [
      "มีกิริยามารยาทสุภาพ เรียบร้อย บุคลิกภาพดี และมีทักษะการต้อนรับ",
      "มีความประณีต ละเอียดรอบคอบในเรื่องธรรมเนียมและพิธีการ",
      "สามารถแก้ไขปัญหาเฉพาะหน้าในพิธีการได้อย่างนุ่มนวล",
    ],
    openSlots: 8,
    tags: ["Protocol", "Hospitality", "Ceremony", "Etiquette"],
    bannerGradient: "from-[#eccb7d]/20 via-[#fbf3e0]/40 to-white",
  },
  {
    id: "venue",
    nameTh: "ฝ่ายสถานที่ (Venue & Facilities)",
    nameEn: "Logistics, Stage Tech & Facilities",
    badge: "สถานที่ & ระบบเวที",
    icon: "Hammer",
    color: "#b08b5f",
    shortDesc: "จัดเตรียมห้องเรียน ห้องพัก เวที เครื่องเสียง โปรเจกเตอร์ และควบคุมระบบเทคนิค",
    description:
      "ผู้อยู่เบื้องหลังความราบรื่นของทุกพื้นที่ จัดผังสถานที่ ติดตั้งเครื่องเสียง ไฟ เวที โปรเจกเตอร์ และขนย้ายอุปกรณ์สำคัญตลอดการจัดกิจกรรม",
    responsibilities: [
      "ประสานงานและจัดเตรียมห้องประชุม ห้องปฏิบัติการคอมพิวเตอร์ และหอพัก",
      "ควบคุมระบบเครื่องเสียง ไมโครโฟน โปรเจกเตอร์ และไฟในทุกช่วงกิจกรรม",
      "ดูแลระบบไฟฟ้า ระบบอินเทอร์เน็ตสำรอง และอุปกรณ์ส่วนกลาง",
      "ดูแลความเรียบร้อย ความสะอาด และจัดเก็บสถานที่หลังเสร็จสิ้นกิจกรรม",
    ],
    qualifications: [
      "มีความคล่องตัวสูง แข็งแรง พร้อมลุยและทำงานเชิงช่าง/เทคนิค",
      "เข้าใจการต่อสายสัญญาณ อุปกรณ์เสียง หรืออุปกรณ์คอมพิวเตอร์พื้นฐาน",
      "มีความคิดรอบคอบเรื่องความปลอดภัยในสถานที่จัดงาน",
    ],
    openSlots: 12,
    tags: ["Stage Tech", "Audio & Visual", "Venue Setup", "Problem Solver"],
    bannerGradient: "from-[#b08b5f]/20 via-[#d98e89]/20 to-white",
  },
  {
    id: "catering-welfare",
    nameTh: "ฝ่ายอาหารและสวัสดิการ (Catering & Welfare)",
    nameEn: "Catering & Hospitality Nutrition",
    badge: "อาหาร & สวัสดิการ",
    icon: "Utensils",
    color: "#eccb7d",
    shortDesc: "จัดเตรียมอาหารหลัก ของว่าง เบรกเครื่องดื่ม และควบคุมคุณภาพสุขอนามัย",
    description:
      "เติมพลังให้ชาว Comclick ทุกคน! วางแผนเมนูอาหาร สั่งซื้อวัตถุดิบ จัดเตรียมเบรก จัดสรรอาหารตามข้อจำกัด (ฮาลาล, มังสวิรัติ, แพ้อาหาร) ให้ตรงเวลาและอิ่มอร่อย",
    responsibilities: [
      "ประสานงานร้านอาหารและแม่ครัวในการจัดเตรียมมื้อหลัก 3 มื้อต่อวัน",
      "จัดเตรียมของว่าง ขนม ผลไม้ และจุดบริการน้ำดื่มตามห้องกิจกรรม",
      "คัดแยกและตรวจสอบอาหารพิเศษ (ฮาลาล / มังสวิรัติ / อาหารปลอดสารแพ้)",
      "ดูแลสุขอนามัยและความสะอาดของจุดรับประทานอาหาร",
    ],
    qualifications: [
      "บริหารจัดการเวลาได้ดีมาก ทำงานแข่งกับเวลาได้",
      "มีความพิถีพิถัน สะอาด มีใจบริการ",
      "รักงานสนับสนุนและพร้อมดูแลให้ทุกคนอิ่มท้องและมีพลัง",
    ],
    openSlots: 10,
    tags: ["Food & Beverage", "Logistics", "Nutrition", "Time Management"],
    bannerGradient: "from-[#eccb7d]/20 via-[#5e97d3]/20 to-white",
  },
];

export const TIMELINE: CampTimelineItem[] = [
  {
    phase: "01",
    date: "1 กันยายน - 30 กันยายน 2569",
    title: "เปิดรับสมัครพี่ค่ายออนไลน์ (Staff Application)",
    description: "กรอกข้อมูล ประวัติการทำกิจกรรม และเลือกฝ่ายที่ต้องการผ่านระบบออนไลน์",
    status: "active",
    highlight: true,
  },
  {
    phase: "02",
    date: "3 ตุลาคม 2569",
    title: "ประกาศรายชื่อผู้มีสิทธิ์เข้ารับการสัมภาษณ์",
    description: "ตรวจสอบรายชื่อ รอบเวลา และสถานที่/ห้องสัมภาษณ์ผ่านระบบหน้าเว็บ",
    status: "upcoming",
  },
  {
    phase: "03",
    date: "5 - 6 ตุลาคม 2569",
    title: "วันสัมภาษณ์คัดเลือกพี่ค่าย (Interview Days)",
    description: "สัมภาษณ์แบบตัวต่อตัวและประเมินทักษะการทำงานเป็นทีม ณ อาคารศึกษาศาสตร์",
    status: "upcoming",
  },
  {
    phase: "04",
    date: "8 ตุลาคม 2569",
    title: "ประกาศผลการคัดเลือกตัวจริง & ยืนยันสิทธิ์",
    description: "ประกาศรายชื่อพี่ค่ายตัวจริงทุกฝ่าย และเปิดให้กดยืนยันสิทธิ์เข้าร่วมทีม",
    status: "upcoming",
  },
  {
    phase: "05",
    date: "10 - 16 ตุลาคม 2569",
    title: "First Meeting & Staff Camp Preparation",
    description: "ประชุมรวมทุกฝ่าย เวิร์กช็อปเตรียมความพร้อม ซ้อมกิจกรรม และจัดแล็บคอมพิวเตอร์",
    status: "upcoming",
  },
  {
    phase: "06",
    date: "17 - 19 ตุลาคม 2569",
    title: "วันจัดกิจกรรม ค่าย ComClick ครั้งที่ 20",
    description: "3 วัน 2 คืน แห่งการจุดประกายเทคโนโลยี ส่งต่อรอยยิ้มและความรู้สู่น้องๆ",
    status: "upcoming",
    highlight: true,
  },
];

export const CAMP_STATS: CampStat[] = [
  {
    label: "ปีแห่งความต่อเนื่อง",
    value: "20+",
    subtext: "ทศวรรษที่ 2 สานต่อความสำเร็จ",
    icon: "Award",
  },
  {
    label: "น้องค่ายที่เข้าร่วม",
    value: "120+",
    subtext: "นักเรียนมัธยมทั่วภาคอีสาน",
    icon: "Users",
  },
  {
    label: "เปิดรับสมัครพี่ค่าย",
    value: "100+",
    subtext: "11 ฝ่ายปฏิบัติการมืออาชีพ",
    icon: "UserPlus",
  },
  {
    label: "กิจกรรม & Workshop",
    value: "15+",
    subtext: "Coding, AI, Robot, Rally",
    icon: "Code",
  },
];

export const FAQS: FaqItem[] = [
  {
    category: "qualification",
    question: "ไม่ได้เรียนสายคอมพิวเตอร์ หรือเขียนโค้ดไม่เป็น สามารถสมัครได้ไหม?",
    answer:
      "สามารถสมัครได้ทุกคนครับ! ค่าย Comclick 20 เปิดรับนักศึกษาทุกชั้นปีและทุกสาขาวิชา โดยเรามีฝ่ายที่หลากหลาย ทั้งสันทนาการ สื่อมีเดีย ประชาสัมพันธ์ จัดหาทุน ปกครอง พิธีการ สวัสดิการ อาหาร และสถานที่ ซึ่งไม่จำเป็นต้องมีความรู้ด้านการเขียนโค้ดเลย เพียงแค่มีใจรักในการทำค่ายและพร้อมเรียนรู้ไปด้วยกัน",
  },
  {
    category: "qualification",
    question: "อยู่ชั้นปีที่ 1 เพิ่งเข้าเรียน สมัครได้ไหม มีผลต่อการพิจารณาหรือไม่?",
    answer:
      "น้องๆ ปี 1 สมัครได้เลยครับ และยินดีต้อนรับมากๆ การคัดเลือกเราดูจากความตั้งใจ ทัศนคติ และความพร้อมในการร่วมกิจกรรมเป็นหลัก ไม่จำกัดชั้นปี มีพี่ๆ คอยเทรนและแนะนำการทำงานอย่างใกล้ชิด",
  },
  {
    category: "interview",
    question: "การสัมภาษณ์มีรูปแบบอย่างไร และควรเตรียมตัวอย่างไร?",
    answer:
      "การสัมภาษณ์เป็นแบบสบายๆ เป็นกันเอง เพื่อทำความรู้จักตัวตน ทัศนคติ และความสนใจในฝ่ายที่เลือก แนะนำให้เป็นตัวของตัวเองอย่างจริงใจ หากมีผลงานหรือภาพกิจกรรมที่เคยทำ สามารถนำมาเปิดให้พี่ๆ ดูได้เลย",
  },
  {
    category: "activity",
    question: "ช่วงเตรียมงาน (10-16 ต.ค.) ต้องเข้าร่วมทุกวันไหม?",
    answer:
      "การเตรียมงานจะมีทั้งการนัดหมายรวมและนัดหมายเฉพาะฝ่าย หากติดเรียนหรือติดภารกิจสำคัญ สามารถแจ้งหัวหน้าฝ่ายล่วงหน้าได้ แต่ขอความร่วมมือเข้าร่วมให้ได้มากที่สุดเพื่อให้งานในวันจริงออกมาสมบูรณ์ที่สุด",
  },
  {
    category: "general",
    question: "เมื่อเสร็จสิ้นการเป็นพี่ค่าย จะได้รับอะไรบ้าง?",
    answer:
      "จะได้รับเกียรติบัตรการเป็นคณะทำงานพี่ค่ายระดับมหาวิทยาลัย (สามารถนำไปยื่นชั่วโมงกิจกรรม / สะสมพอร์ตโฟลิโอได้), เสื้อยืดสตาฟ Comclick 20 ลิมิเต็ด, ประสบการณ์การทำงานจริง และมิตรภาพที่เหนียวแน่นจากเพื่อนๆ พี่น้องหลากสาขา",
  },
];

// Rich Seed Applicants for Demo & Immediate Testing
export const INITIAL_APPLICANTS: Application[] = [
  {
    id: "CC20-2026-0001",
    createdAt: "2026-08-15T09:30:00Z",
    updatedAt: "2026-08-15T09:30:00Z",
    titleTh: "นาย",
    fullNameTh: "ธนภัทร วงศ์เจริญ",
    nicknameTh: "มาร์ค",
    fullNameEn: "Thanaphat Wongcharoen",
    studentId: "653050123-4",
    faculty: "คณะศึกษาศาสตร์",
    major: "สาขาวิชาคอมพิวเตอร์ศึกษา",
    year: "ปี 3",
    phone: "081-234-5678",
    lineId: "mark_cc20",
    facebookOrIg: "fb.com/mark.wong",
    emergencyContact: {
      name: "นางสมพร วงศ์เจริญ",
      relation: "มารดา",
      phone: "089-999-8888",
    },
    shirtSize: "L",
    diet: "ทั่วไป (อาหารปกติ)",
    medicalConditions: "ไม่มี",
    canJoinPreparation: true,
    canJoinCampDates: true,
    firstChoiceDeptId: "academic",
    secondChoiceDeptId: "tech-pr",
    reasonToApply:
      "อยากนำความรู้ด้านการสอนเขียนโปรแกรมและ AI ที่เรียนมา มาถ่ายทอดให้กับน้องๆ มัธยม เพื่อจุดประกายแรงบันดาลใจให้เข้าสู่วงการเทคโนโลยี",
    pastExperience:
      "เคยเป็นผู้ช่วยสอนแล็บ Python ในค่าย Comclick 19 และเป็นสตาฟฝ่ายมีเดียงานสัปดาห์วิทยาศาสตร์",
    skillsAndStrengths: "เชี่ยวชาญ Python, Micro:bit, Web Dev อธิบายเข้าใจง่าย ใจเย็น และกระตือรือร้น",
    problemSolvingScenario:
      "หากน้องในห้องแล็บตามเนื้อหาไม่ทัน จะจัดพี่สตาฟประกบตัวต่อตัวและปรับระดับตัวอย่างให้เห็นภาพชัดเจนขึ้น",
    portfolioUrl: "https://github.com/thanaphat-portfolio",
    status: "interview_passed",
    statusNotes: "ทักษะวิชาการดีเยี่ยม มีความพร้อมในการซ้อมสอนแล็บ",
    assignedDeptId: "academic",
    interviewDate: "5 ตุลาคม 2569 เวลา 10:00 น.",
    interviewLocation: "ห้อง 402 อาคารศึกษาศาสตร์ 2",
  },
  {
    id: "CC20-2026-0002",
    createdAt: "2026-08-16T14:15:00Z",
    updatedAt: "2026-08-16T14:15:00Z",
    titleTh: "นางสาว",
    fullNameTh: "กัญญาณัฐ รัตนโชติ",
    nicknameTh: "มิ้นท์",
    fullNameEn: "Kanyanat Rattanachot",
    studentId: "663040456-7",
    faculty: "คณะมนุษยศาสตร์และสังคมศาสตร์",
    major: "สาขาวิชาภาษาอังกฤษ",
    year: "ปี 2",
    phone: "082-987-6543",
    lineId: "mint_kku",
    facebookOrIg: "IG: @minty.kk",
    emergencyContact: {
      name: "นายประสิทธิ์ รัตนโชติ",
      relation: "บิดา",
      phone: "081-111-2222",
    },
    shirtSize: "M",
    diet: "ทั่วไป (อาหารปกติ)",
    medicalConditions: "แพ้กุ้งและอาหารทะเล",
    canJoinPreparation: true,
    canJoinCampDates: true,
    firstChoiceDeptId: "recreation",
    secondChoiceDeptId: "coordination",
    reasonToApply:
      "ชอบกิจกรรมสันทนาการ อยากให้ทุกคนที่มาค่ายนี้ได้รับความสนุก พลังบวก และความทรงจำที่ดีที่สุดกลับไป",
    pastExperience:
      "ประธานฝ่ายสันทนาการค่ายรับน้องคณะมนุษยศาสตร์ และพิธีกรงานประกวดดนตรีสากล มข.",
    skillsAndStrengths: "พลังงานสูง พูดเก่ง กล้าแสดงออก นำเกมและร้องเพลงสันทนาการได้คล่อง",
    problemSolvingScenario:
      "หากบรรยากาศช่วงบ่ายน้องๆ เริ่มง่วง จะเปลี่ยนเป็นเกมขยับร่างกายสั้นๆ 5 นาทีเพื่อรีเซ็ตความสดชื่น",
    portfolioUrl: "https://drive.google.com/mint-mc-portfolio",
    status: "interview_eligible",
    statusNotes: "บุคลิกภาพดีมาก เหมาะกับตำแหน่งพิธีกรและสันทนาการ",
    assignedDeptId: "recreation",
    interviewDate: "5 ตุลาคม 2569 เวลา 13:30 น.",
    interviewLocation: "ห้องประชุมสารสิน อาคาร 1",
  },
  {
    id: "CC20-2026-0003",
    createdAt: "2026-08-17T11:00:00Z",
    updatedAt: "2026-08-17T11:00:00Z",
    titleTh: "นาย",
    fullNameTh: "ชนาธิป ปัญญาวงศ์",
    nicknameTh: "เจมส์",
    fullNameEn: "Chanathip Panyawong",
    studentId: "673050789-0",
    faculty: "คณะวิทยาลัยการคอมพิวเตอร์",
    major: "วิทยาการคอมพิวเตอร์",
    year: "ปี 1",
    phone: "095-456-7890",
    lineId: "james.cp",
    facebookOrIg: "fb.com/james.panya",
    emergencyContact: {
      name: "นางพรทิพย์ ปัญญาวงศ์",
      relation: "มารดา",
      phone: "086-333-4444",
    },
    shirtSize: "XL",
    diet: "ทั่วไป (อาหารปกติ)",
    medicalConditions: "ไม่มี",
    canJoinPreparation: true,
    canJoinCampDates: true,
    firstChoiceDeptId: "tech-pr",
    secondChoiceDeptId: "academic",
    reasonToApply:
      "อยากฝึกทักษะการถ่ายภาพและงานตัดต่อวิดีโอในค่ายจริง และอยากร่วมเป็นส่วนหนึ่งของค่ายตำนาน Comclick 20",
    pastExperience: "ช่างภาพกิจกรรมโรงเรียนมัธยม และทำช่อง TikTok สรุปความรู้คอมพิวเตอร์",
    skillsAndStrengths:
      "มีกล้อง Sony A7IV เลนส์ 24-70mm ตัดต่อ Premiere Pro และ After Effects ได้คล่อง",
    problemSolvingScenario:
      "เตรียมการ์ดความจำและแบตเตอรี่สำรองหลายชุด พร้อมแบ็กอัปไฟล์ลง SSD ทุกเย็นเพื่อป้องกันงานสูญหาย",
    portfolioUrl: "https://instagram.com/james_photo_kku",
    status: "submitted",
    statusNotes: "รอตรวจสอบใบสมัคร",
  },
  {
    id: "CC20-2026-0004",
    createdAt: "2026-08-18T08:45:00Z",
    updatedAt: "2026-08-18T08:45:00Z",
    titleTh: "นางสาว",
    fullNameTh: "พิมพาภรณ์ ศรีสุวรรณ",
    nicknameTh: "แพรว",
    fullNameEn: "Pimpaporn Srisuwan",
    studentId: "653020345-1",
    faculty: "คณะพยาบาลศาสตร์",
    major: "พยาบาลศาสตรบัณฑิต",
    year: "ปี 3",
    phone: "084-555-6789",
    lineId: "praew.nurse",
    emergencyContact: {
      name: "นายสมชาย ศรีสุวรรณ",
      relation: "บิดา",
      phone: "081-444-5555",
    },
    shirtSize: "S",
    diet: "ทั่วไป (อาหารปกติ)",
    medicalConditions: "ไม่มี",
    canJoinPreparation: true,
    canJoinCampDates: true,
    firstChoiceDeptId: "medical",
    secondChoiceDeptId: "catering-welfare",
    reasonToApply:
      "อยากนำทักษะการปฐมพยาบาลและการดูแลสุขภาพมาช่วยดูแลความปลอดภัยของน้องๆ และทีมงานในค่ายตลอดทั้ง 3 วัน",
    pastExperience: "ผ่านการอบรม Basic Life Support (BLS & CPR) และเป็นฝ่ายพยาบาลค่ายอาสา มข.",
    skillsAndStrengths: "การปฐมพยาบาลเบื้องต้น การประเมินสัญญาณชีพ ความใจเย็นและรับฟัง",
    problemSolvingScenario:
      "หากมีน้องเป็นลมหรือมีไข้ จะแยกเข้าห้องพยาบาลที่มีอากาศถ่ายเท วัดไข้ ให้น้ำเกลือแร่ และประสานงานโรงพยาบาลทันทีหากอาการไม่ดีขึ้น",
    status: "confirmed",
    statusNotes: "ยืนยันสิทธิ์เรียบร้อย",
    assignedDeptId: "medical",
  },
];
